# ***Import Libraries***

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import ExtraTreesClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import VotingClassifier
import folium
from folium.plugins import HeatMap
import plotly.express as px
%matplotlib inline
pd.set_option('display.max_columns', 32)
plt.style.use('fivethirtyeight')

# ***Raed Data***

In [ ]:
df=pd.read_csv('/content/hotel_booking.csv',sep=';')

In [ ]:
len(df)

1000

In [ ]:
df2 = pd.read_csv('/content/id.csv')   # The second file with a single column

# Ensure that the single column in df2 will be added as the first column
# If df2 has only one column, get its name
df2_column_name = df2.columns[0]

# Concatenate df2 as the first column of df
# We need to reset the index of df2 to make sure the rows align properly
df = pd.concat([df2, df], axis=1)

In [ ]:
emp_id = pd.read_csv('/content/id_copy.csv')

In [ ]:
df = pd.concat([df, emp_id], axis=1)

In [ ]:
df.head(5)

,BookingID,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,...,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,empID
0,1,Resort Hotel,0,342,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,...,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,01/07/15,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322,1
1,2,Resort Hotel,0,737,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,...,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,01/07/15,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157,2
2,3,Resort Hotel,0,7,2015,July,27,1,0,1,1,0,0,BB,GBR,Direct,...,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,02/07/15,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734,3
3,4,Resort Hotel,0,13,2015,July,27,1,0,1,1,0,0,BB,GBR,Corporate,...,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,02/07/15,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677,4
4,5,Resort Hotel,0,14,2015,July,27,1,0,2,2,0,0,BB,GBR,Online TA,...,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,03/07/15,Linda Hines,LHines@verizon.com,713-226-5883,************5498,5

# ***Data Checks to Perform***


*   Check Missing values
*   Check Duplicates
*   Check data type
*   Check the number of unique values of each column
*   Check statistics of the dataset
*   Check various categories present in the different categorical columns

# ***Exploratory Data Analysis 📊***

In [ ]:
df.head(5)

,BookingID,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,...,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,empID
0,1,Resort Hotel,0,342,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,...,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,01/07/15,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322,1
1,2,Resort Hotel,0,737,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,...,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,01/07/15,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157,2
2,3,Resort Hotel,0,7,2015,July,27,1,0,1,1,0,0,BB,GBR,Direct,...,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,02/07/15,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734,3
3,4,Resort Hotel,0,13,2015,July,27,1,0,1,1,0,0,BB,GBR,Corporate,...,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,02/07/15,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677,4
4,5,Resort Hotel,0,14,2015,July,27,1,0,2,2,0,0,BB,GBR,Online TA,...,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,03/07/15,Linda Hines,LHines@verizon.com,713-226-5883,************5498,5

In [ ]:
df.tail()

,BookingID,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,...,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,empID
995,996,Resort Hotel,1,122,2015,August,33,9,2,4,2,0,0,HB,PRT,Online TA,...,0,No Deposit,240.0,NaN,0,Transient,166.0,0,2,Canceled,27/05/15,Christina Collins,Christina_Collins@yandex.com,629-364-3798,************4977,996
996,997,Resort Hotel,1,41,2015,August,33,9,2,4,2,0,0,BB,PRT,Online TA,...,0,No Deposit,240.0,NaN,0,Transient,202.0,0,2,Canceled,17/07/15,Katherine Parsons,KatherineParsons@gmail.com,837-549-5190,************5190,997
997,998,Resort Hotel,1,41,2015,August,33,9,2,4,2,0,0,BB,PRT,Online TA,...,0,No Deposit,240.0,NaN,0,Transient,172.0,0,2,Canceled,17/07/15,Christian Bailey,Christian.Bailey@gmail.com,880-193-6472,************5125,998
998,999,Resort Hotel,0,81,2015,August,33,9,2,4,2,1,1,FB,ESP,Direct,...,0,No Deposit,250.0,NaN,0,Transient,277.0,1,1,Check-Out,15/08/15,Mr. William Bell,Mr..B@mail.com,401-188-7246,************6274,999
999,1000,Resort Hotel,0,59,2015,August,33,9,2,5,2,0,0,BB,GBR,Offline TA/TO,...,0,No Deposit,243.0,NaN,0,Transient,104.0,0,0,Check-Out,16/08/15,James Haynes,Haynes.James@hotmail.com,711-535-8794,************8511,1000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   BookingID                       1000 non-null   int64
 1   hotel                           1000 non-null   object
 2   is_canceled                     1000 non-null   int64
 3   lead_time                       1000 non-null   int64
 4   arrival_date_year               1000 non-null   int64
 5   arrival_date_month              1000 non-null   object
 6   arrival_date_week_number        1000 non-null   int64
 7   arrival_date_day_of_month       1000 non-null   int64
 8   stays_in_weekend_nights         1000 non-null   int64
 9   stays_in_week_nights            1000 non-null   int64
 10  adults                          1000 non-null   int64
 11  children                        1000 non-null   int64
 12  babies                          1000 non-null   int64
 13  meal                            1000 non-null   object
 14  country                         999 non-null    object
 15  market_segment                  1000 non-null   object
 16  distribution_channel            1000 non-null   object
 17  is_repeated_guest               1000 non-null   int64
 18  previous_cancellations          1000 non-null   int64
 19  previous_bookings_not_canceled  1000 non-null   int64
 20  reserved_room_type              1000 non-null   object
 21  assigned_room_type              1000 non-null   object
 22  booking_changes                 1000 non-null   int64
 23  deposit_type                    1000 non-null   object
 24  agent                           904 non-null    float64
 25  company                         12 non-null     float64
 26  days_in_waiting_list            1000 non-null   int64
 27  customer_type                   1000 non-null   object
 28  adr                             1000 non-null   float64
 29  required_car_parking_spaces     1000 non-null   int64
 30  total_of_special_requests       1000 non-null   int64
 31  reservation_status              1000 non-null   object
 32  reservation_status_date         1000 non-null   object
 33  name                            1000 non-null   object
 34  email                           1000 non-null   object
 35  phone-number                    1000 non-null   object
 36  credit_card                     1000 non-null   object
 37  empID                           1000 non-null   int64
dtypes: float64(3), int64(19), object(16)
memory usage: 297.0+ KB

In [ ]:
df.describe()

,BookingID,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,empID
count,1000.000000,1000.000000,1000.00000,1000.0,1000.000000,1000.00000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.0,1000.0,1000.0,1000.000000,904.000000,12.000000,1000.0,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,0.322000,57.81200,2015.0,29.463000,13.61400,1.328000,3.48200,1.994000,0.213000,0.024000,0.0,0.0,0.0,0.196000,212.250000,165.583333,0.0,131.950760,0.138000,0.788000,500.500000
std,288.819436,0.467477,56.67531,0.0,1.609727,9.00089,1.076836,2.16665,0.337754,0.638779,0.159529,0.0,0.0,0.0,0.560266,68.295183,62.794699,0.0,45.794436,0.347961,0.881949,288.819436
min,1.000000,0.000000,0.00000,2015.0,27.000000,1.00000,0.000000,0.00000,1.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,2.000000,110.000000,0.0,0.000000,0.000000,0.000000,1.000000
25%,250.750000,0.000000,22.75000,2015.0,28.000000,6.00000,0.000000,2.00000,2.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,240.000000,110.000000,0.0,105.657500,0.000000,0.000000,250.750000
50%,500.500000,0.000000,50.00000,2015.0,29.000000,12.00000,1.500000,3.00000,2.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,240.000000,149.000000,0.0,127.565000,0.000000,1.000000,500.500000
75%,750.250000,1.000000,81.00000,2015.0,31.000000,20.00000,2.000000,5.00000,2.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,240.000000,193.500000,0.0,159.050000,0.000000,1.000000,750.250000
max,1000.000000,1.000000,737.00000,2015.0,33.000000,31.00000,6.000000,15.00000,4.000000,10.000000,2.000000,0.0,0.0,0.0,5.000000,306.000000,270.000000,0.0,280.740000,2.000000,4.000000,1000.000000

In [ ]:
df.shape

(1000, 38)

In [ ]:
df.columns

Index(['BookingID', 'hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'name', 'email',
       'phone-number', 'credit_card', 'empID'],
      dtype='object')

In [ ]:
df.describe(include = 'object')

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status,reservation_status_date,name,email,phone-number,credit_card
count,1000,1000,1000,999,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
unique,1,2,3,34,6,3,8,9,1,4,3,108,992,999,1000,944
top,Resort Hotel,July,BB,PRT,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,17/07/15,Jessica Anderson,James_B@hotmail.com,669-792-1661,************1563
freq,1000,842,744,644,575,788,484,356,1000,873,678,49,2,2,1,3

In [ ]:
df['reservation_status_date']= pd.to_datetime(df['reservation_status_date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   BookingID                       1000 non-null   int64
 1   hotel                           1000 non-null   object
 2   is_canceled                     1000 non-null   int64
 3   lead_time                       1000 non-null   int64
 4   arrival_date_year               1000 non-null   int64
 5   arrival_date_month              1000 non-null   object
 6   arrival_date_week_number        1000 non-null   int64
 7   arrival_date_day_of_month       1000 non-null   int64
 8   stays_in_weekend_nights         1000 non-null   int64
 9   stays_in_week_nights            1000 non-null   int64
 10  adults                          1000 non-null   int64
 11  children                        1000 non-null   int64
 12  babies                          1000 non-null   int64
 13  meal                            1000 non-null   object
 14  country                         999 non-null    object
 15  market_segment                  1000 non-null   object
 16  distribution_channel            1000 non-null   object
 17  is_repeated_guest               1000 non-null   int64
 18  previous_cancellations          1000 non-null   int64
 19  previous_bookings_not_canceled  1000 non-null   int64
 20  reserved_room_type              1000 non-null   object
 21  assigned_room_type              1000 non-null   object
 22  booking_changes                 1000 non-null   int64
 23  deposit_type                    1000 non-null   object
 24  agent                           904 non-null    float64
 25  company                         12 non-null     float64
 26  days_in_waiting_list            1000 non-null   int64
 27  customer_type                   1000 non-null   object
 28  adr                             1000 non-null   float64
 29  required_car_parking_spaces     1000 non-null   int64
 30  total_of_special_requests       1000 non-null   int64
 31  reservation_status              1000 non-null   object
 32  reservation_status_date         1000 non-null   datetime64[ns]
 33  name                            1000 non-null   object
 34  email                           1000 non-null   object
 35  phone-number                    1000 non-null   object
 36  credit_card                     1000 non-null   object
 37  empID                           1000 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(19), object(15)
memory usage: 297.0+ KB

In [ ]:
df.rename(columns = {
    'adults': 'no_of_adults',
    'children': 'no_of_children',
    'stays_in_weekend_nights': 'no_of_weekend_nights',
    'stays_in_week_nights': 'no_of_week_nights',
    'meal': 'type_of_meal_plan',
    'required_car_parking_spaces': 'required_car_parking_space',
    'reserved_room_type': 'room_type_reserved',
    'lead_time': 'lead_time',
    'arrival_date_year': 'arrival_year',
    'arrival_date_month': 'arrival_month',
    'arrival_date_day_of_month': 'arrival_day',
    'market_segment': 'market_segment_type',
    'is_repeated_guest': 'repeated_guest',
    'previous_cancellations': 'no_of_previous_cancellations',
    'previous_bookings_not_canceled': 'no_of_previous_bookings_not_canceled',
    'adr': 'avg_price_per_room',
    'total_of_special_requests': 'no_of_special_requests',
    'is_canceled': 'booking_status'
}, inplace=True)

In [ ]:
df['arrival_month'] = df['arrival_month'].map({
    'January': 1, 'February': 2, 'March': 3, 'April': 4,
    'May': 5, 'June': 6, 'July': 7, 'August': 8,
    'September': 9, 'October': 10, 'November': 11, 'December': 12
})

In [ ]:
#df['reservation_date'] = df['reservation_status_date'].dt.strftime('%Y-%m-%d')

In [ ]:
df.head(10)

,BookingID,hotel,booking_status,lead_time,arrival_year,arrival_month,arrival_date_week_number,arrival_day,no_of_weekend_nights,no_of_week_nights,no_of_adults,no_of_children,babies,type_of_meal_plan,country,market_segment_type,...,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,avg_price_per_room,required_car_parking_space,no_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,empID
0,1,Resort Hotel,0,342,2015,7,27,1,0,0,2,0,0,BB,PRT,Direct,...,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-01-07,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322,1
1,2,Resort Hotel,0,737,2015,7,27,1,0,0,2,0,0,BB,PRT,Direct,...,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-01-07,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157,2
2,3,Resort Hotel,0,7,2015,7,27,1,0,1,1,0,0,BB,GBR,Direct,...,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-02-07,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734,3
3,4,Resort Hotel,0,13,2015,7,27,1,0,1,1,0,0,BB,GBR,Corporate,...,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-02-07,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677,4
4,5,Resort Hotel,0,14,2015,7,27,1,0,2,2,0,0,BB,GBR,Online TA,...,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-03-07,Linda Hines,LHines@verizon.com,713-226-5883,************5498,5
5,6,Resort Hotel,0,14,2015,7,27,1,0,2,2,0,0,BB,GBR,Online TA,...,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-03-07,Jasmine Fletcher,JFletcher43@xfinity.com,190-271-6743,************9263,6
6,7,Resort Hotel,0,0,2015,7,27,1,0,2,2,0,0,BB,PRT,Direct,...,0,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-03-07,Dylan Rangel,Rangel.Dylan@comcast.net,420-332-5209,************6994,7
7,8,Resort Hotel,0,9,2015,7,27,1,0,2,2,0,0,FB,PRT,Direct,...,0,No Deposit,303.0,NaN,0,Transient,103.0,0,1,Check-Out,2015-03-07,William Velez,Velez_William@mail.com,286-669-4333,************8729,8
8,9,Resort Hotel,1,85,2015,7,27,1,0,3,2,0,0,BB,PRT,Online TA,...,0,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-06-05,Steven Murphy,Steven.Murphy54@aol.com,341-726-5787,************3639,9
9,10,Resort Hotel,1,75,2015,7,27,1,0,3,2,0,0,HB,PRT,Offline TA/TO,...,0,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22,Michael Moore,MichaelMoore81@outlook.com,316-648-6176,************9190,10

In [ ]:
df['type_of_meal_plan'] = \
df['type_of_meal_plan'].map({
        'BB': 'Bed and Breakfass', 'HB': 'Half Board', 'SC': 'Self Catering', 'FB': 'Full Board'
    })

In [ ]:
df.tail(5)

,BookingID,hotel,booking_status,lead_time,arrival_year,arrival_month,arrival_date_week_number,arrival_day,no_of_weekend_nights,no_of_week_nights,no_of_adults,no_of_children,babies,type_of_meal_plan,country,market_segment_type,...,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,avg_price_per_room,required_car_parking_space,no_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,empID
995,996,Resort Hotel,1,122,2015,8,33,9,2,4,2,0,0,Half Board,PRT,Online TA,...,0,No Deposit,240.0,NaN,0,Transient,166.0,0,2,Canceled,2015-05-27,Christina Collins,Christina_Collins@yandex.com,629-364-3798,************4977,996
996,997,Resort Hotel,1,41,2015,8,33,9,2,4,2,0,0,Bed and Breakfass,PRT,Online TA,...,0,No Deposit,240.0,NaN,0,Transient,202.0,0,2,Canceled,2015-07-17,Katherine Parsons,KatherineParsons@gmail.com,837-549-5190,************5190,997
997,998,Resort Hotel,1,41,2015,8,33,9,2,4,2,0,0,Bed and Breakfass,PRT,Online TA,...,0,No Deposit,240.0,NaN,0,Transient,172.0,0,2,Canceled,2015-07-17,Christian Bailey,Christian.Bailey@gmail.com,880-193-6472,************5125,998
998,999,Resort Hotel,0,81,2015,8,33,9,2,4,2,1,1,Full Board,ESP,Direct,...,0,No Deposit,250.0,NaN,0,Transient,277.0,1,1,Check-Out,2015-08-15,Mr. William Bell,Mr..B@mail.com,401-188-7246,************6274,999
999,1000,Resort Hotel,0,59,2015,8,33,9,2,5,2,0,0,Bed and Breakfass,GBR,Offline TA/TO,...,0,No Deposit,243.0,NaN,0,Transient,104.0,0,0,Check-Out,2015-08-16,James Haynes,Haynes.James@hotmail.com,711-535-8794,************8511,1000

# ***Data Pre-processing***

# check missing data

In [ ]:
df.isnull().sum()

BookingID                                 0
hotel                                     0
booking_status                            0
lead_time                                 0
arrival_year                              0
arrival_month                             0
arrival_date_week_number                  0
arrival_day                               0
no_of_weekend_nights                      0
no_of_week_nights                         0
no_of_adults                              0
no_of_children                            0
babies                                    0
type_of_meal_plan                         0
country                                   1
market_segment_type                       0
distribution_channel                      0
repeated_guest                            0
no_of_previous_cancellations              0
no_of_previous_bookings_not_canceled      0
room_type_reserved                        0
assigned_room_type                        0
booking_changes                           0
deposit_type                              0
agent                                    96
company                                 988
days_in_waiting_list                      0
customer_type                             0
avg_price_per_room                        0
required_car_parking_space                0
no_of_special_requests                    0
reservation_status                        0
reservation_status_date                   0
name                                      0
email                                     0
phone-number                              0
credit_card                               0
empID                                     0
dtype: int64

In [ ]:
max_null_val=df.isnull().sum().idxmax()
print('The maximum number of Null data is in column *** ',max_null_val,' ***')

The maximum number of Null data is in column ***  company  ***

In [ ]:
#remove company column
df=df.drop(['company'], axis = 1)

In [ ]:
#remove null rows in country column
df = df.dropna(subset=['country'])

In [ ]:
#filling null values with zero in agent column
df['agent'] = df['agent'].fillna(0)

In [ ]:
df.isnull().sum()

BookingID                               0
hotel                                   0
booking_status                          0
lead_time                               0
arrival_year                            0
arrival_month                           0
arrival_date_week_number                0
arrival_day                             0
no_of_weekend_nights                    0
no_of_week_nights                       0
no_of_adults                            0
no_of_children                          0
babies                                  0
type_of_meal_plan                       0
country                                 0
market_segment_type                     0
distribution_channel                    0
repeated_guest                          0
no_of_previous_cancellations            0
no_of_previous_bookings_not_canceled    0
room_type_reserved                      0
assigned_room_type                      0
booking_changes                         0
deposit_type                            0
agent                                   0
days_in_waiting_list                    0
customer_type                           0
avg_price_per_room                      0
required_car_parking_space              0
no_of_special_requests                  0
reservation_status                      0
reservation_status_date                 0
name                                    0
email                                   0
phone-number                            0
credit_card                             0
empID                                   0
dtype: int64

In [ ]:
df.head(5)

,BookingID,hotel,booking_status,lead_time,arrival_year,arrival_month,arrival_date_week_number,arrival_day,no_of_weekend_nights,no_of_week_nights,no_of_adults,no_of_children,babies,type_of_meal_plan,country,market_segment_type,...,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,avg_price_per_room,required_car_parking_space,no_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,empID
0,1,Resort Hotel,0,342,2015,7,27,1,0,0,2,0,0,Bed and Breakfass,PRT,Direct,...,C,3,No Deposit,0.0,0,Transient,0.0,0,0,Check-Out,2015-01-07,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322,1
1,2,Resort Hotel,0,737,2015,7,27,1,0,0,2,0,0,Bed and Breakfass,PRT,Direct,...,C,4,No Deposit,0.0,0,Transient,0.0,0,0,Check-Out,2015-01-07,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157,2
2,3,Resort Hotel,0,7,2015,7,27,1,0,1,1,0,0,Bed and Breakfass,GBR,Direct,...,C,0,No Deposit,0.0,0,Transient,75.0,0,0,Check-Out,2015-02-07,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734,3
3,4,Resort Hotel,0,13,2015,7,27,1,0,1,1,0,0,Bed and Breakfass,GBR,Corporate,...,A,0,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-02-07,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677,4
4,5,Resort Hotel,0,14,2015,7,27,1,0,2,2,0,0,Bed and Breakfass,GBR,Online TA,...,A,0,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-03-07,Linda Hines,LHines@verizon.com,713-226-5883,************5498,5

In [ ]:
#Check for duplicate rows
df.duplicated().sum()

0

In [ ]:
#Check data types before Processing
df.dtypes

BookingID                                        int64
hotel                                           object
booking_status                                   int64
lead_time                                        int64
arrival_year                                     int64
arrival_month                                    int64
arrival_date_week_number                         int64
arrival_day                                      int64
no_of_weekend_nights                             int64
no_of_week_nights                                int64
no_of_adults                                     int64
no_of_children                                   int64
babies                                           int64
type_of_meal_plan                               object
country                                         object
market_segment_type                             object
distribution_channel                            object
repeated_guest                                   int64
no_of_previous_cancellations                     int64
no_of_previous_bookings_not_canceled             int64
room_type_reserved                              object
assigned_room_type                              object
booking_changes                                  int64
deposit_type                                    object
agent                                          float64
days_in_waiting_list                             int64
customer_type                                   object
avg_price_per_room                             float64
required_car_parking_space                       int64
no_of_special_requests                           int64
reservation_status                              object
reservation_status_date                 datetime64[ns]
name                                            object
email                                           object
phone-number                                    object
credit_card                                     object
empID                                            int64
dtype: object

In [ ]:
#  columns are merged into one
df['arrival_date'] = df['arrival_year'].map(str) + '-' +df['arrival_month'].map(str) + '-' \
                       + df['arrival_day'].map(str)

In [ ]:
df.head(10)

,BookingID,hotel,booking_status,lead_time,arrival_year,arrival_month,arrival_date_week_number,arrival_day,no_of_weekend_nights,no_of_week_nights,no_of_adults,no_of_children,babies,type_of_meal_plan,country,market_segment_type,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,avg_price_per_room,required_car_parking_space,no_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,empID,arrival_date
0,1,Resort Hotel,0,342,2015,7,27,1,0,0,2,0,0,Bed and Breakfass,PRT,Direct,...,3,No Deposit,0.0,0,Transient,0.0,0,0,Check-Out,2015-01-07,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322,1,2015-7-1
1,2,Resort Hotel,0,737,2015,7,27,1,0,0,2,0,0,Bed and Breakfass,PRT,Direct,...,4,No Deposit,0.0,0,Transient,0.0,0,0,Check-Out,2015-01-07,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157,2,2015-7-1
2,3,Resort Hotel,0,7,2015,7,27,1,0,1,1,0,0,Bed and Breakfass,GBR,Direct,...,0,No Deposit,0.0,0,Transient,75.0,0,0,Check-Out,2015-02-07,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734,3,2015-7-1
3,4,Resort Hotel,0,13,2015,7,27,1,0,1,1,0,0,Bed and Breakfass,GBR,Corporate,...,0,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-02-07,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677,4,2015-7-1
4,5,Resort Hotel,0,14,2015,7,27,1,0,2,2,0,0,Bed and Breakfass,GBR,Online TA,...,0,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-03-07,Linda Hines,LHines@verizon.com,713-226-5883,************5498,5,2015-7-1
5,6,Resort Hotel,0,14,2015,7,27,1,0,2,2,0,0,Bed and Breakfass,GBR,Online TA,...,0,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-03-07,Jasmine Fletcher,JFletcher43@xfinity.com,190-271-6743,************9263,6,2015-7-1
6,7,Resort Hotel,0,0,2015,7,27,1,0,2,2,0,0,Bed and Breakfass,PRT,Direct,...,0,No Deposit,0.0,0,Transient,107.0,0,0,Check-Out,2015-03-07,Dylan Rangel,Rangel.Dylan@comcast.net,420-332-5209,************6994,7,2015-7-1
7,8,Resort Hotel,0,9,2015,7,27,1,0,2,2,0,0,Full Board,PRT,Direct,...,0,No Deposit,303.0,0,Transient,103.0,0,1,Check-Out,2015-03-07,William Velez,Velez_William@mail.com,286-669-4333,************8729,8,2015-7-1
8,9,Resort Hotel,1,85,2015,7,27,1,0,3,2,0,0,Bed and Breakfass,PRT,Online TA,...,0,No Deposit,240.0,0,Transient,82.0,0,1,Canceled,2015-06-05,Steven Murphy,Steven.Murphy54@aol.com,341-726-5787,************3639,9,2015-7-1
9,10,Resort Hotel,1,75,2015,7,27,1,0,3,2,0,0,Half Board,PRT,Offline TA/TO,...,0,No Deposit,15.0,0,Transient,105.5,0,0,Canceled,2015-04-22,Michael Moore,MichaelMoore81@outlook.com,316-648-6176,************9190,10,2015-7-1

In [ ]:
#df['reservation_status_date'] = df['reservation_status_date'].apply(lambda x: x.replace(month=7, day=1))

In [ ]:
df['arrival_date'] = pd.to_datetime(df['arrival_date'], errors='coerce').dt.strftime('%Y-%m-%d')

In [ ]:
#df['arrival_date'] = pd.to_datetime(df['arrival_date'], format='%Y-%B-%d')
#df['arrival_date'] = df['arrival_date'].dt.strftime('%Y-%m-%d')

In [ ]:
df.tail(20)

,BookingID,hotel,booking_status,lead_time,arrival_year,arrival_month,arrival_date_week_number,arrival_day,no_of_weekend_nights,no_of_week_nights,no_of_adults,no_of_children,babies,type_of_meal_plan,country,market_segment_type,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,avg_price_per_room,required_car_parking_space,no_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,empID,arrival_date
980,981,Resort Hotel,0,98,2015,8,32,8,2,5,2,0,0,Half Board,PRT,Offline TA/TO,...,0,No Deposit,127.0,0,Transient,138.00,0,0,Check-Out,2015-08-15,Joel Ball,JBall98@hotmail.com,804-266-6202,************4096,981,2015-08-08
981,982,Resort Hotel,1,91,2015,8,32,8,2,5,2,0,0,Bed and Breakfass,PRT,Online TA,...,0,No Deposit,240.0,0,Transient,134.00,0,1,Canceled,2015-05-14,Kyle Lynch,Kyle_Lynch69@att.com,192-714-9819,************7438,982,2015-08-08
982,983,Resort Hotel,1,58,2015,8,32,8,2,6,1,0,0,Bed and Breakfass,PRT,Direct,...,1,No Deposit,250.0,0,Transient,173.00,0,0,Canceled,2015-07-20,Patricia Coleman,Patricia.Coleman@outlook.com,264-195-0004,************2862,983,2015-08-08
983,984,Resort Hotel,0,61,2015,8,32,8,4,9,2,0,0,Bed and Breakfass,FRA,Online TA,...,0,No Deposit,240.0,0,Transient,165.69,1,0,Check-Out,2015-08-21,Eileen Rivera,EileenRivera@hotmail.com,155-629-6379,************5560,984,2015-08-08
984,985,Resort Hotel,0,0,2015,8,33,9,1,0,2,0,0,Bed and Breakfass,PRT,Direct,...,0,No Deposit,0.0,0,Transient,195.00,0,0,Check-Out,2015-10-08,Jose Bradley,Jose.Bradley@zoho.com,529-511-6356,************3859,985,2015-08-09
985,986,Resort Hotel,0,5,2015,8,33,9,1,0,2,0,0,Bed and Breakfass,PRT,Online TA,...,0,No Deposit,306.0,0,Transient,127.31,0,0,Check-Out,2015-10-08,Mark Williams,Mark_Williams86@xfinity.com,114-150-8445,************1818,986,2015-08-09
986,987,Resort Hotel,0,2,2015,8,33,9,1,0,2,0,0,Bed and Breakfass,PRT,Online TA,...,0,No Deposit,240.0,0,Transient,134.00,0,1,Check-Out,2015-10-08,Nathaniel Lewis,NLewis84@verizon.com,669-909-5201,************4758,987,2015-08-09
987,988,Resort Hotel,1,9,2015,8,33,9,2,0,2,1,0,Bed and Breakfass,PRT,Direct,...,0,No Deposit,250.0,0,Transient,207.00,0,2,Canceled,2015-01-08,Toni Watkins,Watkins_Toni87@verizon.com,498-324-5863,************7077,988,2015-08-09
988,989,Resort Hotel,1,10,2015,8,33,9,2,0,2,0,0,Bed and Breakfass,PRT,Online TA,...,0,No Deposit,240.0,0,Transient,211.50,0,1,Canceled,2015-07-30,Marie Mitchell,MMitchell@protonmail.com,400-376-9213,************5286,989,2015-08-09
989,990,Resort Hotel,0,62,2015,8,33,9,2,1,2,0,0,Bed and Breakfass,FRA,Online TA,...,1,No Deposit,240.0,0,Transient,210.33,1,2,Check-Out,2015-12-08,Helen Pierce,Helen_P@protonmail.com,297-405-9734,************1749,990,2015-08-09
990,991,Resort Hotel,0,34,2015,8,33,9,2,2,2,0,0,Bed and Breakfass,USA,Online TA,...,0,No Deposit,240.0,0,Transient,211.00,0,1,Check-Out,2015-08-13,Tommy Brown,Brown_Tommy@comcast.net,955-290-5243,************5694,991,2015-08-09
991,992,Resort Hotel,0,82,2015,8,33,9,2,2,2,0,0,Bed and Breakfass,CN,Online TA,...,0,No Deposit,240.0,0,Transient,154.00,0,0,Check-Out,2015-08-13,Matthew Phillips,Matthew_P@comcast.net,423-681-4059,************2610,992,2015-08-09
992,993,Resort Hotel,1,65,2015,8,33,9,2,3,2,0,0,Bed and Breakfass,PRT,Online TA,...,0,No Deposit,240.0,0,Transient,145.40,0,0,Canceled,2015-06-22,Lisa Johnson,LJohnson60@protonmail.com,752-349-7608,************2047,993,2015-08-09
993,994,Resort Hotel,1,129,2015,8,33,9,2,3,1,0,0,Bed and Breakfass,PRT,Online TA,...,0,No Deposit,240.0,0,Transient,101.25,0,0,Canceled,2015-06-04,David Hernandez,Hernandez_David@zoho.com,970-378-4358,************2253,994,2015-08-09
994,995,Resort Hotel,0,55,2015,8,33,9,2,4,2,0,0,Half Board,MEX,Online TA,...,0,No Deposit,242.0,0,Transient,179.38,0,0,Check-Out,2015-08-15,Tracy Stewart,Stewart.Tracy60@protonmail.com,611-327-4624,************8354,995,2015-08-09
995,996,Resort Hotel,1,122,2015,8,33,9,2,4,2,0,0,Half Board,PRT,Online TA,...,0,No Deposit,240.0,0,Transient,166.00,0,2,Canceled,2015-05-27,Christina Collins,Christina_Collins@yandex.com,629-364-3798,************4977,996,2015-08-09
996,997,Resort Hotel,1,41,2015,8,33,9,2,4,2,0,0,Bed and Breakfass,PRT,Online TA,...,0,No Deposit,240.0,0,Transient,202.00,0,2,Canceled,2015-07-17,Katherine Parsons,KatherineParsons@gmail.com,837-549-5190,************5190,997,2015-08-09
997,998,Resort Hotel,1,41,2015,8,33,9,2,4,2,0,0,Bed and Breakfass,PRT,Online TA,...,0,No Deposit,240.0,0,Transient,172.00,0,2,Canceled,2015-07-17,Christian Bailey,Christian.Bailey@gmail.com,880-193-6472,************5125,998,2015-08-09
998,999,Resort Hotel,0,81,2015,8,33,9,2,4,2,1,1,Full Board,ESP,Direct,...,0,No Deposit,250.0,0,Transient,277.00,1,1,Check-Out,2015-08-15,Mr. William Bell,Mr..B@mail.com,401-188-7246,************6274,999,2015-08-09
999,1000,Resort Hotel,0,59,2015,8,33,9,2,5,2,0,0,Bed and Breakfass,GBR,Offline TA/TO,...,0,No Deposit,243.0,0,Transient,104.00,0,0,Check-Out,2015-08-16,James Haynes,Haynes.James@hotmail.com,711-535-8794,************8511,1000,2015-08-09

In [ ]:
df['arrival_date']= pd.to_datetime(df['arrival_date'])

In [ ]:
#Check data types before Processing.  2015-08-09
df.dtypes

BookingID                                        int64
hotel                                           object
booking_status                                   int64
lead_time                                        int64
arrival_year                                     int64
arrival_month                                    int64
arrival_date_week_number                         int64
arrival_day                                      int64
no_of_weekend_nights                             int64
no_of_week_nights                                int64
no_of_adults                                     int64
no_of_children                                   int64
babies                                           int64
type_of_meal_plan                               object
country                                         object
market_segment_type                             object
distribution_channel                            object
repeated_guest                                   int64
no_of_previous_cancellations                     int64
no_of_previous_bookings_not_canceled             int64
room_type_reserved                              object
assigned_room_type                              object
booking_changes                                  int64
deposit_type                                    object
agent                                          float64
days_in_waiting_list                             int64
customer_type                                   object
avg_price_per_room                             float64
required_car_parking_space                       int64
no_of_special_requests                           int64
reservation_status                              object
reservation_status_date                 datetime64[ns]
name                                            object
email                                           object
phone-number                                    object
credit_card                                     object
empID                                            int64
arrival_date                            datetime64[ns]
dtype: object

In [ ]:
# Calculating total guests for each record
df['Total Guests'] = df['no_of_adults'] + df['no_of_children']

In [ ]:
df.head(10)

,BookingID,hotel,booking_status,lead_time,arrival_year,arrival_month,arrival_date_week_number,arrival_day,no_of_weekend_nights,no_of_week_nights,no_of_adults,no_of_children,babies,type_of_meal_plan,country,market_segment_type,...,deposit_type,agent,days_in_waiting_list,customer_type,avg_price_per_room,required_car_parking_space,no_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,empID,arrival_date,Total Guests
0,1,Resort Hotel,0,342,2015,7,27,1,0,0,2,0,0,Bed and Breakfass,PRT,Direct,...,No Deposit,0.0,0,Transient,0.0,0,0,Check-Out,2015-01-07,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322,1,2015-07-01,2
1,2,Resort Hotel,0,737,2015,7,27,1,0,0,2,0,0,Bed and Breakfass,PRT,Direct,...,No Deposit,0.0,0,Transient,0.0,0,0,Check-Out,2015-01-07,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157,2,2015-07-01,2
2,3,Resort Hotel,0,7,2015,7,27,1,0,1,1,0,0,Bed and Breakfass,GBR,Direct,...,No Deposit,0.0,0,Transient,75.0,0,0,Check-Out,2015-02-07,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734,3,2015-07-01,1
3,4,Resort Hotel,0,13,2015,7,27,1,0,1,1,0,0,Bed and Breakfass,GBR,Corporate,...,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-02-07,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677,4,2015-07-01,1
4,5,Resort Hotel,0,14,2015,7,27,1,0,2,2,0,0,Bed and Breakfass,GBR,Online TA,...,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-03-07,Linda Hines,LHines@verizon.com,713-226-5883,************5498,5,2015-07-01,2
5,6,Resort Hotel,0,14,2015,7,27,1,0,2,2,0,0,Bed and Breakfass,GBR,Online TA,...,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-03-07,Jasmine Fletcher,JFletcher43@xfinity.com,190-271-6743,************9263,6,2015-07-01,2
6,7,Resort Hotel,0,0,2015,7,27,1,0,2,2,0,0,Bed and Breakfass,PRT,Direct,...,No Deposit,0.0,0,Transient,107.0,0,0,Check-Out,2015-03-07,Dylan Rangel,Rangel.Dylan@comcast.net,420-332-5209,************6994,7,2015-07-01,2
7,8,Resort Hotel,0,9,2015,7,27,1,0,2,2,0,0,Full Board,PRT,Direct,...,No Deposit,303.0,0,Transient,103.0,0,1,Check-Out,2015-03-07,William Velez,Velez_William@mail.com,286-669-4333,************8729,8,2015-07-01,2
8,9,Resort Hotel,1,85,2015,7,27,1,0,3,2,0,0,Bed and Breakfass,PRT,Online TA,...,No Deposit,240.0,0,Transient,82.0,0,1,Canceled,2015-06-05,Steven Murphy,Steven.Murphy54@aol.com,341-726-5787,************3639,9,2015-07-01,2
9,10,Resort Hotel,1,75,2015,7,27,1,0,3,2,0,0,Half Board,PRT,Offline TA/TO,...,No Deposit,15.0,0,Transient,105.5,0,0,Canceled,2015-04-22,Michael Moore,MichaelMoore81@outlook.com,316-648-6176,************9190,10,2015-07-01,2

In [ ]:
print(df.apply(lambda col: col.unique()))

BookingID                               [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
hotel                                                                      [Resort Hotel]
booking_status                                                                     [0, 1]
lead_time                               [342, 737, 7, 13, 14, 0, 9, 85, 75, 23, 35, 68...
arrival_year                                                                       [2015]
arrival_month                                                                      [7, 8]
arrival_date_week_number                                     [27, 28, 29, 30, 31, 32, 33]
arrival_day                             [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
no_of_weekend_nights                                                   [0, 1, 2, 4, 3, 6]
no_of_week_nights                              [0, 1, 2, 3, 4, 5, 11, 8, 10, 6, 7, 15, 9]
no_of_adults                                                                 [2, 1, 3, 4]
no_of_children                                                              [0, 1, 2, 10]
babies                                                                          [0, 1, 2]
type_of_meal_plan                             [Bed and Breakfass, Full Board, Half Board]
country                                 [PRT, GBR, USA, ESP, IRL, FRA, ROU, NOR, OMN, ...
market_segment_type                     [Direct, Corporate, Online TA, Offline TA/TO, ...
distribution_channel                                           [Direct, Corporate, TA/TO]
repeated_guest                                                                        [0]
no_of_previous_cancellations                                                          [0]
no_of_previous_bookings_not_canceled                                                  [0]
room_type_reserved                                               [C, A, D, E, G, F, H, L]
assigned_room_type                                            [C, A, D, E, G, F, I, B, H]
booking_changes                                                        [3, 4, 0, 1, 2, 5]
deposit_type                                                                 [No Deposit]
agent                                   [0.0, 304.0, 240.0, 303.0, 15.0, 241.0, 8.0, 2...
days_in_waiting_list                                                                  [0]
customer_type                               [Transient, Contract, Transient-Party, Group]
avg_price_per_room                      [0.0, 75.0, 98.0, 107.0, 103.0, 82.0, 105.5, 1...
required_car_parking_space                                                      [0, 1, 2]
no_of_special_requests                                                    [0, 1, 3, 2, 4]
reservation_status                                         [Check-Out, Canceled, No-Show]
reservation_status_date                 [2015-01-07 00:00:00, 2015-02-07 00:00:00, 201...
name                                    [Ernest Barnes, Andrea Baker, Rebecca Parker, ...
email                                   [Ernest.Barnes31@outlook.com, Andrea_Baker94@a...
phone-number                            [669-792-1661, 858-637-6955, 652-885-2745, 364...
credit_card                             [************4322, ************9157, *********...
empID                                   [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
arrival_date                            [2015-07-01 00:00:00, 2015-07-02 00:00:00, 201...
Total Guests                                                          [2, 1, 3, 4, 5, 12]
dtype: object

In [ ]:
#drop columns that has only 0 value
df = df.drop(['repeated_guest', 'no_of_previous_cancellations','no_of_previous_bookings_not_canceled','days_in_waiting_list'], axis=1)

In [ ]:
print(df.apply(lambda col: col.unique()))

BookingID                     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
hotel                                                            [Resort Hotel]
booking_status                                                           [0, 1]
lead_time                     [342, 737, 7, 13, 14, 0, 9, 85, 75, 23, 35, 68...
arrival_year                                                             [2015]
arrival_month                                                            [7, 8]
arrival_date_week_number                           [27, 28, 29, 30, 31, 32, 33]
arrival_day                   [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
no_of_weekend_nights                                         [0, 1, 2, 4, 3, 6]
no_of_week_nights                    [0, 1, 2, 3, 4, 5, 11, 8, 10, 6, 7, 15, 9]
no_of_adults                                                       [2, 1, 3, 4]
no_of_children                                                    [0, 1, 2, 10]
babies                                                                [0, 1, 2]
type_of_meal_plan                   [Bed and Breakfass, Full Board, Half Board]
country                       [PRT, GBR, USA, ESP, IRL, FRA, ROU, NOR, OMN, ...
market_segment_type           [Direct, Corporate, Online TA, Offline TA/TO, ...
distribution_channel                                 [Direct, Corporate, TA/TO]
room_type_reserved                                     [C, A, D, E, G, F, H, L]
assigned_room_type                                  [C, A, D, E, G, F, I, B, H]
booking_changes                                              [3, 4, 0, 1, 2, 5]
deposit_type                                                       [No Deposit]
agent                         [0.0, 304.0, 240.0, 303.0, 15.0, 241.0, 8.0, 2...
customer_type                     [Transient, Contract, Transient-Party, Group]
avg_price_per_room            [0.0, 75.0, 98.0, 107.0, 103.0, 82.0, 105.5, 1...
required_car_parking_space                                            [0, 1, 2]
no_of_special_requests                                          [0, 1, 3, 2, 4]
reservation_status                               [Check-Out, Canceled, No-Show]
reservation_status_date       [2015-01-07 00:00:00, 2015-02-07 00:00:00, 201...
name                          [Ernest Barnes, Andrea Baker, Rebecca Parker, ...
email                         [Ernest.Barnes31@outlook.com, Andrea_Baker94@a...
phone-number                  [669-792-1661, 858-637-6955, 652-885-2745, 364...
credit_card                   [************4322, ************9157, *********...
empID                         [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
arrival_date                  [2015-07-01 00:00:00, 2015-07-02 00:00:00, 201...
Total Guests                                                [2, 1, 3, 4, 5, 12]
dtype: object

In [ ]:
print(df['arrival_date'].to_string(index=False))

2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-01
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-02
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-03
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-04
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-05
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-06
2015-07-07
2015-07-07
2015-07-07
2015-07-07
2015-07-07
2015-07-07
2015-07-07
2015-07-07
2015-07-07
2015-07-07
2015-07-07
2015-07-07
2015-07-07
2015-07-07
2015-07-07
2015-07-07
2015-07-07
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-08
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-09
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-10
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-11
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-12
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-13
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-14
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-15
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-16
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-17
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-18
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-19
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-20
2015-07-21
2015-07-21
2015-07-21
2015-07-21
2015-07-21
2015-07-21
2015-07-21
2015-07-21
2015-07-21
2015-07-21
2015-07-21
2015-07-21
2015-07-22
2015-07-22
2015-07-22
2015-07-22
2015-07-22
2015-07-22
2015-07-22
2015-07-23
2015-07-23
2015-07-23
2015-07-23
2015-07-23
2015-07-23
2015-07-23
2015-07-23
2015-07-23
2015-07-23
2015-07-23
2015-07-23
2015-07-23
2015-07-23
2015-07-23
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-24
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-25
2015-07-26
2015-07-26
2015-07-26
2015-07-26
2015-07-26
2015-07-26
2015-07-26
2015-07-26
2015-07-26
2015-07-26
2015-07-26
2015-07-26
2015-07-26
2015-07-26
2015-07-26
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-27
2015-07-28
2015-07-28
2015-07-28
2015-07-28
2015-07-28
2015-07-28
2015-07-28
2015-07-28
2015-07-28
2015-07-28
2015-07-28
2015-07-28
2015-07-28
2015-07-28
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-29
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-30
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-07-31
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-01
2015-08-02
2015-08-02
2015-08-02
2015-08-02
2015-08-02
2015-08-02
2015-08-02
2015-08-02
2015-08-02
2015-08-02
2015-08-02
2015-08-02
2015-08-03
2015-08-03
2015-08-03
2015-08-03
2015-08-03
2015-08-03
2015-08-03
2015-08-03
2015-08-03
2015-08-03
2015-08-03
2015-08-04
2015-08-04
2015-08-04
2015-08-04
2015-08-04
2015-08-04
2015-08-04
2015-08-04
2015-08-04
2015-08-04
2015-08-04
2015-08-04
2015-08-04
2015-08-04
2015-08-05
2015-08-05
2015-08-05
2015-08-05
2015-08-05
2015-08-05
2015-08-05
2015-08-05
2015-08-05
2015-08-05
2015-08-05
2015-08-05
2015-08-05
2015-08-05
2015-08-06
2015-08-06
2015-08-06
2015-08-06
2015-08-06
2015-08-06
2015-08-06
2015-08-06
2015-08-06
2015-08-06
2015-08-06
2015-08-06
2015-08-06
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-07
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-08
2015-08-09
2015-08-09
2015-08-09
2015-08-09
2015-08-09
2015-08-09
2015-08-09
2015-08-09
2015-08-09
2015-08-09
2015-08-09
2015-08-09
2015-08-09
2015-08-09
2015-08-09
2015-08-09

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999 entries, 0 to 999
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   BookingID                   999 non-null    int64
 1   hotel                       999 non-null    object
 2   booking_status              999 non-null    int64
 3   lead_time                   999 non-null    int64
 4   arrival_year                999 non-null    int64
 5   arrival_month               999 non-null    int64
 6   arrival_date_week_number    999 non-null    int64
 7   arrival_day                 999 non-null    int64
 8   no_of_weekend_nights        999 non-null    int64
 9   no_of_week_nights           999 non-null    int64
 10  no_of_adults                999 non-null    int64
 11  no_of_children              999 non-null    int64
 12  babies                      999 non-null    int64
 13  type_of_meal_plan           999 non-null    object
 14  country                     999 non-null    object
 15  market_segment_type         999 non-null    object
 16  distribution_channel        999 non-null    object
 17  room_type_reserved          999 non-null    object
 18  assigned_room_type          999 non-null    object
 19  booking_changes             999 non-null    int64
 20  deposit_type                999 non-null    object
 21  agent                       999 non-null    float64
 22  customer_type               999 non-null    object
 23  avg_price_per_room          999 non-null    float64
 24  required_car_parking_space  999 non-null    int64
 25  no_of_special_requests      999 non-null    int64
 26  reservation_status          999 non-null    object
 27  reservation_status_date     999 non-null    datetime64[ns]
 28  name                        999 non-null    object
 29  email                       999 non-null    object
 30  phone-number                999 non-null    object
 31  credit_card                 999 non-null    object
 32  empID                       999 non-null    int64
 33  arrival_date                999 non-null    datetime64[ns]
 34  Total Guests                999 non-null    int64
dtypes: datetime64[ns](2), float64(2), int64(17), object(14)
memory usage: 281.0+ KB

In [ ]:
df.head(5)

,BookingID,hotel,booking_status,lead_time,arrival_year,arrival_month,arrival_date_week_number,arrival_day,no_of_weekend_nights,no_of_week_nights,no_of_adults,no_of_children,babies,type_of_meal_plan,country,market_segment_type,...,booking_changes,deposit_type,agent,customer_type,avg_price_per_room,required_car_parking_space,no_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,empID,arrival_date,Total Guests
0,1,Resort Hotel,0,342,2015,7,27,1,0,0,2,0,0,Bed and Breakfass,PRT,Direct,...,3,No Deposit,0.0,Transient,0.0,0,0,Check-Out,2015-01-07,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322,1,2015-07-01,2
1,2,Resort Hotel,0,737,2015,7,27,1,0,0,2,0,0,Bed and Breakfass,PRT,Direct,...,4,No Deposit,0.0,Transient,0.0,0,0,Check-Out,2015-01-07,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157,2,2015-07-01,2
2,3,Resort Hotel,0,7,2015,7,27,1,0,1,1,0,0,Bed and Breakfass,GBR,Direct,...,0,No Deposit,0.0,Transient,75.0,0,0,Check-Out,2015-02-07,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734,3,2015-07-01,1
3,4,Resort Hotel,0,13,2015,7,27,1,0,1,1,0,0,Bed and Breakfass,GBR,Corporate,...,0,No Deposit,304.0,Transient,75.0,0,0,Check-Out,2015-02-07,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677,4,2015-07-01,1
4,5,Resort Hotel,0,14,2015,7,27,1,0,2,2,0,0,Bed and Breakfass,GBR,Online TA,...,0,No Deposit,240.0,Transient,98.0,0,1,Check-Out,2015-03-07,Linda Hines,LHines@verizon.com,713-226-5883,************5498,5,2015-07-01,2

In [ ]:
cols = [col for col in df.columns if col != 'empID'] + ['empID']
df = df[cols]

In [ ]:
len(df)

999

In [ ]:
df.tail(5)

,BookingID,hotel,booking_status,lead_time,arrival_year,arrival_month,arrival_date_week_number,arrival_day,no_of_weekend_nights,no_of_week_nights,no_of_adults,no_of_children,babies,type_of_meal_plan,country,market_segment_type,...,booking_changes,deposit_type,agent,customer_type,avg_price_per_room,required_car_parking_space,no_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,arrival_date,Total Guests,empID
995,996,Resort Hotel,1,122,2015,8,33,9,2,4,2,0,0,Half Board,PRT,Online TA,...,0,No Deposit,240.0,Transient,166.0,0,2,Canceled,2015-05-27,Christina Collins,Christina_Collins@yandex.com,629-364-3798,************4977,2015-08-09,2,996
996,997,Resort Hotel,1,41,2015,8,33,9,2,4,2,0,0,Bed and Breakfass,PRT,Online TA,...,0,No Deposit,240.0,Transient,202.0,0,2,Canceled,2015-07-17,Katherine Parsons,KatherineParsons@gmail.com,837-549-5190,************5190,2015-08-09,2,997
997,998,Resort Hotel,1,41,2015,8,33,9,2,4,2,0,0,Bed and Breakfass,PRT,Online TA,...,0,No Deposit,240.0,Transient,172.0,0,2,Canceled,2015-07-17,Christian Bailey,Christian.Bailey@gmail.com,880-193-6472,************5125,2015-08-09,2,998
998,999,Resort Hotel,0,81,2015,8,33,9,2,4,2,1,1,Full Board,ESP,Direct,...,0,No Deposit,250.0,Transient,277.0,1,1,Check-Out,2015-08-15,Mr. William Bell,Mr..B@mail.com,401-188-7246,************6274,2015-08-09,3,999
999,1000,Resort Hotel,0,59,2015,8,33,9,2,5,2,0,0,Bed and Breakfass,GBR,Offline TA/TO,...,0,No Deposit,243.0,Transient,104.0,0,0,Check-Out,2015-08-16,James Haynes,Haynes.James@hotmail.com,711-535-8794,************8511,2015-08-09,2,1000

In [ ]:
len(df)

999

In [ ]:
# Save the cleaned dataset to the new CSV file.
df.to_csv('cleaned_hotel_booking.csv', index=False)

# **sentiment** **analysis**

In [ ]:
#read data
data=pd.read_csv('/content/hotel_Reviews.tsv',sep='\t')

In [ ]:
data.insert(0, 'revID', range(1, len(data) + 1))

In [ ]:
data.head(5)

   revID                                             Review  Liked
0      1                           Wow... Loved this place.      1
1      2                                 Crust is not good.      0
2      3          Not tasty and the texture was just nasty.      0
3      4  Stopped by during the late May bank holiday of...      1
4      5  The selection on the menu was great and so wer...      1

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   revID   1000 non-null   int64
 1   Review  1000 non-null   object
 2   Liked   1000 non-null   int64
dtypes: int64(2), object(1)
memory usage: 23.6+ KB

In [ ]:
data['Liked'].value_counts()

Liked
1    500
0    500
Name: count, dtype: int64

In [ ]:
data['Review'].apply(len)

0       24
1       18
2       41
3       87
4       59
      ...
995     66
996     24
997     50
998     91
999    134
Name: Review, Length: 1000, dtype: int64

In [ ]:
data['Review'].apply(len).max()

149

In [ ]:
#pre-processing

#import string
#string.punctuation

In [ ]:
import nltk
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
print(stopwords.words('english')) #list of words that we can remove from our text

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

In [ ]:
s=data['Review'][0]
s

'Wow... Loved this place.'

In [ ]:
import re
re.sub('[^a-zA-Z]'," ",s)

'Wow    Loved this place '

In [ ]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [ ]:
corpus = []

for i in range(len(data)):
  s = re.sub('[^a-zA-Z]'," ",data['Review'][i])
  s = s.lower()
  s = s.split() #tokniziation
  s=[word for word in s if not word in stopwords.words('english')] #remove stop word
  s=' '.join(s) #convert to string
  s = ps.stem(s) #remove suffixes
  corpus.append(s)

corpus

['wow loved plac',
 'crust good',
 'tasty texture nasti',
 'stopped late may bank holiday rick steve recommendation lov',
 'selection menu great pric',
 'getting angry want damn pho',
 'honeslty taste fresh',
 'potatoes like rubber could tell made ahead time kept warm',
 'fries great',
 'great touch',
 'service prompt',
 'would go back',
 'cashier care ever say still ended wayyy overpr',
 'tried cape cod ravoli chicken cranberry mmmm',
 'disgusted pretty sure human hair',
 'shocked signs indicate cash',
 'highly recommend',
 'waitress little slow servic',
 'place worth time let alone vega',
 'like',
 'burrittos blah',
 'food amaz',
 'service also cut',
 'could care less interior beauti',
 'perform',
 'right red velvet cake ohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street tacos friendly staff',
 'took hour get food tables restaurant food luke warm sever running around like totally overwhelm',
 'worst salmon sashimi',
 'also combos like burger fries beer decent d',
 'like final blow',
 'found place accident could happi',
 'seems like good quick place grab bite familiar pub food favor look elsewher',
 'overall like place lot',
 'redeeming quality restaurant inexpens',
 'ample portions good pric',
 'poor service waiter made feel like stupid every time came t',
 'first visit hiro delight',
 'service suck',
 'shrimp tender moist',
 'deal good enough would drag establish',
 'hard judge whether sides good grossed melted styrofoam want eat fear getting sick',
 'positive note server attentive provided great servic',
 'frozen pucks disgust worst people behind regist',
 'thing like prime rib dessert sect',
 'bad food damn gener',
 'burger good beef cooked right',
 'want sandwich go firehous',
 'side greek salad greek dressing tasty pita hummus refresh',
 'ordered duck rare pink tender inside nice char outsid',
 'came running us realized husband left sunglasses t',
 'chow mein good',
 'horrible attitudes towards customers talk one customers enjoy food',
 'portion hug',
 'loved friendly servers great food wonderful imaginative menu',
 'heart attack grill downtown vegas absolutely flat lined excuse restaur',
 'much seafood like strings pasta bottom',
 'salad right amount sauce power scallop perfectly cook',
 'ripped banana ripped petrified tasteless',
 'least think refill water struggle wave minut',
 'place receives stars appet',
 'cocktails handmade delici',
 'definitely go back',
 'glad found plac',
 'great food service huge portions give military discount',
 'always great time dos gringo',
 'update went back second time still amaz',
 'got food apparently never heard salt batter fish chewi',
 'great way finish great',
 'deal included tastings drinks jeff went beyond expect',
 'really really good rice tim',
 'service meh',
 'took min get milkshake nothing chocolate milk',
 'guess known place would suck inside excalibur use common sens',
 'scallop dish quite appalling value wel',
 'times bad customer servic',
 'sweet potato fries good seasoned wel',
 'today second time lunch buffet pretty good',
 'much good food vegas feel cheated wasting eating opportunity going rice compani',
 'coming like experiencing underwhelming relationship parties wait person ask break',
 'walked place smelled like old grease trap others ',
 'turkey roast beef bland',
 'place',
 'pan cakes everyone raving taste like sugary disaster tailored palate six year old',
 'love pho spring rolls oh yummy tri',
 'poor batter meat ratio made chicken tenders unsatisfi',
 'say food amaz',
 'omelets di',
 'everything fresh delici',
 'summary largely disappointing dining experi',
 'like really sexy party mouth outrageously flirting hottest person parti',
 'never hard rock casino never ever step forward',
 'best breakfast buffet',
 'say bye bye tip ladi',
 'never go',
 'back',
 'food arrived quickli',
 'good',
 'side cafe serves really good food',
 'server fantastic found wife loves roasted garlic bone marrow added extra meal another marrow go',
 'good thing waiter helpful kept bloddy mary com',
 'best buffet town price cannot beat',
 'loved mussels cooked wine reduction duck tender potato dishes delici',
 'one better buffet',
 'went tigerlilly fantastic afternoon',
 'food delicious bartender attentive personable got great d',
 'ambience wonderful music play',
 'go back next trip',
 'sooooo good',
 'real sushi lovers let honest yama good',
 'least min passed us ordering food arriving busi',
 'really fantastic thai restaurant definitely worth visit',
 'nice spicy tend',
 'good pric',
 'check',
 'pretty gross',
 'better atmospher',
 'kind hard mess steak',
 'although much liked look sound place actual experience bit disappoint',
 'know place managed served blandest food ever eaten preparing indian cuisin',
 'worst service boot least worri',
 'service fine waitress friendli',
 'guys steaks steak loving son steak best worst places said best steak ever eaten',
 'thought venture away get good sushi place really hit spot night',
 'host staff lack better word bitch',
 'bland liking place number reasons want waste time bad reviewing leav',
 'phenomenal food service ambi',
 'return',
 'definitely worth venturing strip pork belly return next time vega',
 'place way overpriced mediocre food',
 'penne vodka excel',
 'good selection food including massive meatloaf sandwich crispy chicken wrap delish tuna melt tasty burg',
 'management rud',
 'delicious nyc bagels good selections cream cheese real lox capers even',
 'great subway fact good come every subway meet expect',
 'seriously solid breakfast',
 'one best bars food vega',
 'extremely rude really many restaurants would love dine weekend vega',
 'drink never empty made really great menu suggest',
 '',
 'waiter helpful friendly rarely checked u',
 'husband ate lunch disappointed food servic',
 'red curry much bamboo shoots tasti',
 'nice blanket moz top feel like done cover subpar food',
 'bathrooms clean place well decor',
 'menu always changing food quality going service extremely slow',
 'service little slow considering served people servers food coming slow pac',
 'give thumb',
 'watched waiter pay lot attention tables ignore u',
 'fianc came middle day greeted seated right away',
 'great restaurant mandalay bay',
 'waited forty five minutes vain',
 'crostini came salad stal',
 'highlights great quality nigiri',
 'staff friendly joint always clean',
 'different cut piece day still wonderful tender well well flavor',
 'ordered voodoo pasta first time really excellent pasta since going gluten free several years ago',
 'place good',
 'unfortunately must hit bakery leftover day everything ordered stal',
 'came back today since relocated still impress',
 'seated immedi',
 'menu diverse reasonably pr',
 'avoid cost',
 'restaurant always full never wait',
 'delici',
 'place hands one best places eat phoenix metro area',
 'go looking good food',
 'never treated bad',
 'bacon hella salti',
 'also ordered spinach avocado salad ingredients sad dressing literally zero tast',
 'really vegas fine dining used right menus handed ladies prices list',
 'waitresses friendli',
 'lordy khao soi dish missed curry lov',
 'everything menu terrific also thrilled made amazing accommodations vegetarian daught',
 'perhaps caught night judging reviews inspired go back',
 'service leaves lot desir',
 'atmosphere modern hip maintaining touch cozi',
 'weekly haunt definitely place come back everi',
 'literally sat minutes one asking take ord',
 'burger absolutely flavor meat totally bland burger overcooked charcoal flavor',
 'also decided send back waitress looked like verge heart attack',
 'dressed treated rud',
 'probably dirt',
 'love place hits spot want something healthy lacking quantity flavor',
 'ordered lemon raspberry ice cocktail also incred',
 'food sucked expected sucked could imagin',
 'interesting decor',
 'really like crepe st',
 'also served hot bread butter home made potato chips bacon bits top original good',
 'watch preparing delicious food',
 'egg rolls fantast',
 'order arrived one gyros miss',
 'salad wings ice cream dessert left feeling quite satisfi',
 'really sure joey voted best hot dog valley readers phoenix magazin',
 'best place go tasty bowl pho',
 'live music fridays totally blow',
 'never insulted felt disrespect',
 'friendly staff',
 'worth driv',
 'heard good things place exceeding every hope could dream',
 'food great serivc',
 'warm beer help',
 'great brunch spot',
 'service friendly invit',
 'good lunch spot',
 'lived since first last time stepped foot plac',
 'worst experience ev',
 'must night plac',
 'sides delish mixed mushrooms yukon gold puree white corn beat',
 'bug never showed would given sure side wall bug climbing kitchen',
 'minutes waiting salad realized coming time soon',
 'friend loved salmon tartar',
 'go back',
 'extremely tasti',
 'waitress good though',
 'soggy good',
 'jamaican mojitos delici',
 'small worth pric',
 'food rich order accordingli',
 'shower area outside rinse take full shower unless mind nude everyone se',
 'service bit lack',
 'lobster bisque bussell sprouts risotto filet needed salt pepper course none t',
 'hopefully bodes going business someone cook com',
 'either cold enough flavor bad',
 'loved bacon wrapped d',
 'unbelievable bargain',
 'folks otto always make us feel welcome speci',
 'mains also uninspir',
 'place first pho amaz',
 'wonderful experience made place must stop whenever town',
 'food bad enough enjoy dealing world worst annoying drunk peopl',
 'fun chef',
 'ordered double cheeseburger got single patty falling apart picture uploaded yeah still suck',
 'great place couple drinks watch sporting events walls covered tv',
 'possible give zero star',
 'descriptions said yum yum sauce another said eel sauce yet another said spicy mayo well none rolls sauc',
 'say would hardest decision honestly dishes taste supposed taste amaz',
 'rolled eyes may stayed sure go back tri',
 'everyone attentive providing excellent customer servic',
 'horrible waste time money',
 'dish quite flavour',
 'time side restaurant almost empty excus',
 'busy either also building freezing cold',
 'like reviewer said pay eat plac',
 'drinks took close minutes come one point',
 'seriously flavorful delights folk',
 'much better ayce sushi place went vega',
 'lighting dark enough set mood',
 'based sub par service received effort show gratitude business going back',
 'owner really great peopl',
 'nothing privileged working ',
 'greek dressing creamy flavor',
 'overall think would take parents place made similar complaints silently felt',
 'pizza good peanut sauce tasti',
 'table service pretty fast',
 'fantastic servic',
 'well would given godfathers zero stars poss',
 'know mak',
 'tough short flavor',
 'hope place sticks around',
 'bars vegas ever recall charged tap wat',
 'restaurant atmosphere exquisit',
 'good service clean inexpensive boot',
 'seafood fresh generous port',
 'plus buck',
 'service par eith',
 'thus far visited twice food absolutely delicious tim',
 'good year ago',
 'self proclaimed coffee cafe wildly disappoint',
 'veggitarian platter world',
 'cant go wrong food',
 'beat',
 'stopped place madison ironman friendly kind staff',
 'chefs friendly good job',
 'better dedicated boba tea spots even jenni pho',
 'liked patio service outstand',
 'goat taco skimp meat wow flavor',
 'think',
 'mac salad pretty bland get',
 'went bachi burger friend recommendation disappoint',
 'service stink',
 'waited wait',
 'place quality sushi quality restaur',
 'would definitely recommend wings well pizza',
 'great pizza salad',
 'things went wrong burned saganaki',
 'waited hour breakfast could done times better hom',
 'place amaz',
 'hate disagree fellow yelpers husband disappointed plac',
 'waited hours never got either pizzas many around us came lat',
 'know slow',
 'staff great food delish incredible beer select',
 'live neighborhood disappointed back convenient loc',
 'know pulled pork could soooo delici',
 'get incredibly fresh fish prepared car',
 'go gave star rating please know third time eating bachi burger writing review',
 'love fact everything menu worth',
 'never dining plac',
 'food excellent service good',
 'good beer drink selection good food select',
 'please stay away shrimp stir fried noodl',
 'potato chip order sad could probably count many chips box probably around',
 'food really bor',
 'good service check',
 'greedy corporation never see another dim',
 'never ever go back',
 'much like go back get passed atrocious service never return',
 'summer dine charming outdoor patio delight',
 'expect good',
 'fantastic food',
 'ordered toasted english muffin came untoast',
 'food good',
 'never going back',
 'great food price high quality house mad',
 'bus boy hand rud',
 'point friends basically figured place joke mind making publicly loudly known',
 'back good bbq lighter fare reasonable pricing tell public back old way',
 'considering two us left full happy go wrong',
 'bread made hous',
 'downside servic',
 'also fries without doubt worst fries ev',
 'service exceptional food good review',
 'couple months later returned amazing m',
 'favorite place town shawarrrrrrma',
 'black eyed peas sweet potatoes unr',
 'disappoint',
 'could serve vinaigrette may make better overall dish still good',
 'go far many places never seen restaurant serves egg breakfast especi',
 'mom got home immediately got sick bites salad',
 'servers pleasant deal always honor pizza hut coupon',
 'truly unbelievably good glad went back',
 'fantastic service pleased atmospher',
 'everything gross',
 'love plac',
 'great service food',
 'first bathrooms location dirty seat covers replenished plain yucki',
 'burger got gold standard burger kind disappoint',
 'omg food delicioso',
 'nothing authentic plac',
 'spaghetti nothing special whatsoev',
 'dishes salmon best great',
 'vegetables fresh sauce feels like authentic thai',
 'worth driving tucson',
 'selection probably worst seen vegas non',
 'pretty good beer select',
 'place like chipotle bett',
 'classy warm atmosphere fun fresh appetizers succulent steaks baseball steak',
 'stars brick oven bread app',
 'eaten multiple times time food delici',
 'sat another ten minutes finally gave left',
 'terribl',
 'everyone treated equally speci',
 'take min pancakes egg',
 'delici',
 'good side staff genuinely pleasant enthusiastic real treat',
 'sadly gordon ramsey steak place shall sharply avoid next trip vega',
 'always evening wonderful food delici',
 'best fish ever lif',
 'bathroom next door nic',
 'buffet small food offered bland',
 'outstanding little restaurant best food ever tast',
 'pretty cool would say',
 'definitely turn doubt back unless someone else buy',
 'server great job handling large rowdy t',
 'find wasting food despicable food',
 'wife lobster bisque soup lukewarm',
 'would come back sushi craving vega',
 'staff great ambiance great',
 'deserves star',
 'left stomach ache felt sick rest day',
 'dropped bal',
 'dining space tiny elegantly decorated comfort',
 'customize order way like usual eggplant green bean stir fry lov',
 'beans rice mediocre best',
 'best tacos town far',
 'took back money got outta',
 'interesting part town place amaz',
 'rude inconsiderate manag',
 'staff friendly wait times served horrible one even says hi first minut',
 'back',
 'great dinn',
 'service outshining definitely recommend halibut',
 'food terr',
 'never ever go back told many people happen',
 'recommend unless car breaks front starv',
 'come back every time vega',
 'place deserves one star food',
 'disgrac',
 'def coming back bowl next tim',
 'want healthy authentic ethic food try plac',
 'continue come ladies night andddd date night highly recommend place anyone area',
 'several times past experience always great',
 'walked away stuffed happy first vegas buffet experi',
 'service excellent prices pretty reasonable considering vegas located inside crystals shopping mall aria',
 'summarize food incredible nay transcendant nothing brings joy quite like memory pneumatic condiment dispens',
 'probably one people ever go ians lik',
 'kids pizza always hit lots great side dish options kiddo',
 'service perfect family atmosphere nice se',
 'cooked perfection service impecc',
 'one simply disappoint',
 'overall disappointed quality food bouchon',
 'accountant know getting screw',
 'great place eat reminds little mom pop shops san francisco bay area',
 'today first taste buldogis gourmet hot dog tell ever thought poss',
 'left frustr',
 'definitely soon',
 'food really good got full petty fast',
 'service fantast',
 'total waste tim',
 'know kind best iced tea',
 'come hungry leave happy stuf',
 'service give star',
 'assure disappoint',
 'take little bad service food suck',
 'gave trying eat crust teeth still sor',
 'completely gross',
 'really enjoyed ',
 'first time going think quickly become regular',
 'server nice even though looked little overwhelmed needs stayed professional friendly end',
 'dinner companions told everything fresh nice texture tast',
 'ground right next table large smeared stepped tracked everywhere pile green bird poop',
 'furthermore even find hours operation websit',
 'tried like place times think don',
 'mistak',
 'complaint',
 'seriously good pizza expert connisseur top',
 'waiter jerk',
 'strike wants rush',
 'nicest restaurant owners ever come across',
 'never com',
 'loved biscuit',
 'service quick friendli',
 'ordered appetizer took minutes pizza another minut',
 'absolutley fantast',
 'huge awkward lb piece cow ths gristle fat',
 'definitely come back',
 'like steiners dark feels like bar',
 'wow spicy delici',
 'familiar check',
 'take business dinner dollars elsewher',
 'love go back',
 'anyway fs restaurant wonderful breakfast lunch',
 'nothing speci',
 'day week different deal delici',
 'mention combination pears almonds bacon big winn',
 'back',
 'sauce tasteless',
 'food delicious spicy enough sure ask spicier prefer way',
 'ribeye steak cooked perfectly great mesquite flavor',
 'think going back anytime soon',
 'food gooodd',
 'far sushi connoisseur definitely tell difference good food bad food certainly bad food',
 'insult',
 'last times lunch bad',
 'chicken wings contained driest chicken meat ever eaten',
 'food good enjoyed every mouthful enjoyable relaxed venue couples small family groups etc',
 'nargile think great',
 'best tater tots southwest',
 'loved plac',
 'definitely worth paid',
 'vanilla ice cream creamy smooth profiterole choux pastry fresh enough',
 'im az time new spot',
 'manager worst',
 'inside really quite nice clean',
 'food outstanding prices reason',
 'think running back carly anytime soon food',
 'due fact took minutes acknowledged another minutes get food kept forgetting th',
 'love margarita',
 'first vegas buffet disappoint',
 'good though',
 'one note ventilation could use upgrad',
 'great pork sandwich',
 'waste tim',
 'total letdown would much rather go camelback flower shop cartel coffe',
 'third cheese friend burger cold',
 'enjoy pizza brunch',
 'steaks well trimmed also perfectly cook',
 'group claimed would handled us beauti',
 'love',
 'asked bill leave without eating bring eith',
 'place jewel las vegas exactly hoping find nearly ten years liv',
 'seafood limited boiled shrimp crab legs crab legs definitely taste fresh',
 'selection food best',
 'delicious absolutely back',
 'small family restaurant fine dining establish',
 'toro tartare cavier extraordinary liked thinly sliced wagyu white truffl',
 'dont think back long tim',
 'attached gas station rarely good sign',
 'awesom',
 'back many times soon',
 'menu much good stuff could decid',
 'worse humiliated worker right front bunch horrible name cal',
 'conclusion filling m',
 'daily specials always hit group',
 'tragedy struck',
 'pancake also really good pretty larg',
 'first crawfish experience delici',
 'monster chicken fried steak eggs time favorit',
 'waitress sweet funni',

In [ ]:
type(corpus)

list

In [ ]:
# prompt: convert corpus to dataframe

corpus_df = pd.DataFrame(corpus, columns=['Customer_Review'])
corpus_df

                                       Customer_Review
0                                       wow loved plac
1                                           crust good
2                                  tasty texture nasti
3    stopped late may bank holiday rick steve recom...
4                            selection menu great pric
..                                                 ...
995                     think food flavor texture lack
996                             appetite instantly gon
997                    overall impressed would go back
998  whole experience underwhelming think go ninja ...
999  wasted enough life poured salt wound drawing t...

[1000 rows x 1 columns]

In [ ]:
# prompt: append corpus_df to data in one dataframe and remove review column

# Append corpus_df to data
data_ = pd.concat([data, corpus_df], axis=1)
# Remove 'Review' column
data_ = data_.drop('Review', axis=1)
data_.head()

   revID  Liked                                    Customer_Review
0      1      1                                     wow loved plac
1      2      0                                         crust good
2      3      0                                tasty texture nasti
3      4      1  stopped late may bank holiday rick steve recom...
4      5      1                          selection menu great pric

In [ ]:
data_.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   revID            1000 non-null   int64
 1   Liked            1000 non-null   int64
 2   Customer_Review  1000 non-null   object
dtypes: int64(2), object(1)
memory usage: 23.6+ KB

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [ ]:
x=cv.fit_transform(corpus).toarray()

In [ ]:
#use Naivebase algorithm

In [ ]:
y=data_['Liked']
y

0      1
1      0
2      0
3      1
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: Liked, Length: 1000, dtype: int64

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [ ]:
X_train.shape

(700, 1994)

# **Model Bulding & Training**

In [ ]:
from sklearn.naive_bayes import MultinomialNB #for multi dim
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

In [ ]:
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB()

# **Prediction**

In [ ]:
y_pred=classifier.predict(X_test)

In [ ]:
y_pred

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1])

In [ ]:
y_test.values

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1])

# **Evaluation **

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix:\n",cm)

Confusion Matrix:
 [[107  45]
 [ 30 118]]

In [ ]:
# Accuracy, Precision and Recall
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
score1 = accuracy_score(y_test,y_pred)
score2 = precision_score(y_test,y_pred)
score3= recall_score(y_test,y_pred)
print("\n")
print("Accuracy is ",round(score1*100,2),"%")
print("Precision is ",round(score2,2))
print("Recall is ",round(score3,2))

Accuracy is  75.0 %
Precision is  0.72
Recall is  0.8

In [ ]:

#df2_column_name = df2.columns[0]

# Concatenate df2 as the first column of df
# We need to reset the index of df2 to make sure the rows align properly
data__ = pd.concat([data_, df2], axis=1)

In [ ]:
data__.head()

In [ ]:
# Save the cleaned dataset to the new CSV file.
data__.to_csv('cleaned_review.csv', index=False)